### ISSUE TITLE
Papers Voting Nov 16

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#1]

**Comment by grburgess** [comment]
## Search for Gravitational Waves Associated with Gamma-Ray Bursts Detected by Fermi and Swift During the LIGO-Virgo Run O3a
https://arxiv.org/abs/2010.14550

We search for gravitational-wave transients associated with gamma-ray bursts detected by the Fermi and Swift satellites during the first part of the third observing run of Advanced LIGO and Advanced Virgo (1 April 2019 15:00 UTC - 1 October 2019 15:00 UTC). 105 gamma-ray bursts were analyzed using a search for generic gravitational-wave transients; 32 gamma-ray bursts were analyzed with a search that specifically targets neutron star binary mergers as short gamma-ray burst progenitors. We describe a method to calculate the probability that triggers from the binary merger targeted search are astrophysical and apply that method to the most significant gamma-ray bursts in that search. We find no significant evidence for gravitational-wave signals associated with the gamma-ray bursts that we followed up, nor for a population of unidentified subthreshold signals. We consider several source types and signal morphologies, and report for these lower bounds on the distance to each gamma-ray burst.


### Comments:

I think this is not so interesting but we should discuss a bit as we are loosely related.

**Comment by cescalara** [comment]
## Differential Source Count for Gamma Ray Bursts

https://arxiv.org/abs/2011.03945

In this work, we revisit our earlier attempt to quantify the intrinsic luminosity function N(L)dL of Gamma Ray Bursts (GRBs) using observational constraints on the distribution of intrinsic luminosities. In our earlier work, the median luminosity Lmedian(z) was calculated, as a function of redshift, of beamed, identical, detectable sources of known redshifts, and compared with the luminosities of nearby GRBs of known redshift. In this paper, we constrain N(L)dL from the observed flux distribution N(F)dF by calculating the expected N(F) from a sample of GRBs with {\it unknown} redshift. We compare our theoretical expectations from a physical model with Fermi GBM data and thus constrain the angular emission profile of the GRBs. We find that at wide angles, N(L) is consistent with having a subluminous component, but that it is inconsistent with {\it purely} on-axis viewing.

### Comments:

Could be interesting to talk about the issues with this.

**Comment by BjoernBiltzinger** [comment]
### GW190521 may be an intermediate mass ratio inspiral

https://arxiv.org/pdf/2010.12558.pdf

GW190521  is  the  first  confident  observation  of  a  binary  black  hole  merger  with  total  massM >100 M. Given the lack of observational constraints at these masses, we analyze GW190521 consideringtwo different priors for the binary’s masses:  uniform in mass ratio and source-frame total mass, anduniform  in  source-frame  component  masses.   For  the  uniform  in  mass-ratio  prior,  we  find  that  thecomponent  masses  aremsrc1=  168+15−61Mandmsrc2=  16+33−3M.   The  uniform  in  component-massprior yields a bimodal posterior distribution.  There is a low-mass-ratio mode (q <4) withmsrc1=100+17−18Mandmsrc2= 57+17−16Mand a high-mass-ratio mode (q≥4) withmsrc1= 166+16−35Mandmsrc2= 16+14−3M.  Although the two modes have nearly equal posterior probability,  the maximum-likelihood parameters are in the high-mass ratio mode, withmsrc1= 171Mandmsrc2= 16M, anda  signal-to-noise  ratio  of  16.   These  results  are  consistent  with  the  proposed  “mass  gap”  producedby pair-instability in supernova.  Our results are inconsistent with those published in Abbott et al.(2020b).  We find that a combination of the prior used and the constraints applied may have preventedthat analysis from sampling the high-mass-ratio mode.  An accretion flare in AGN J124942.3+344929was  observed  in  possible  coincidence  with  GW190521  by  the  Zwicky  Transient  Facility  (ZTF).  Wereport parameters assuming a common origin; however, the spatial agreement of GW190521 and theEM flare alone does not provide convincing evidence for the association (lnB&−4).

**Comments:**

An interesting application of the Dynesty nested sampler

**Comment by grburgess** [comment]
## A backscattering dominated prompt emission model for the prompt phase of Gamma ray bursts

https://arxiv.org/abs/2011.02973


As gamma-ray burst (GRB) jet drills its way through the collapsing star, it traps a baryonic cork ahead of it. Here we explore a prompt emission model for GRBs in which the jet does not cross the cork, but rather photons that are emitted deep in the flow are scattered inside the expanding cork and escape largely from the back end of it as they push it from behind. Due to the relativistic motion of the cork, these photons are easily seen by an observer close to the jet axis peaking at εpeak∼few×100keV. We show that this model naturally explains several key observational features including: (1) Low energy spectral slope α∼1, and high energy power law index β1−2to−5 with an intermediate thermal spectral region; (2) decay of the prompt emission light curve as ∼t−2; (3) Delay of soft photons; (4) peak energy - isotropic energy (the so-called Amati) correlation, εpeak∼εmiso, with m∼0.45, resulting from different viewing angles. At low luminosities, our model predicts an observable turn off in the Amati relation with m∼0.3. (4) An anti-correlation between the spectral FWHM and time as t−1. (5) Temporal evolution εpeak∼t−1, with increase of the high energy spectral slope with time. (6) Distribution of peak energies εpeak in the observed GRB population. We discuss the consequence of our model in view of the current and future prompt emission observations.

### Comments

Particularly annoyed at the citations for synchrotron. Francesco might have particular interest in this.

**Comment by fberlato** [comment]
### Search for sub-TeV neutrino emission from transient sources with three years of IceCube data

https://arxiv.org/abs/2011.05096

Since the discovery of a flux of high-energy astrophysical neutrinos, searches for their origins have focused primarily at TeV-PeV energies. Compared to sub-TeV searches, high-energy searches benefit from an increase in the neutrino cross section, improved angular resolution on the neutrino direction, and a reduced background from atmospheric neutrinos and muons. However, the focus on high energy does not preclude the existence of sub-TeV neutrino emission where IceCube retains sensitivity. Here we present the first all-flavor search from IceCube for transient emission of low-energy neutrinos, between 1-100 GeV using three years of data obtained with the IceCube-DeepCore detector. We find no evidence of transient neutrino emission in the data, thus leading to a constraint on the volumetric rate of astrophysical transient sources in the range of ∼705−2301Gpc−3yr−1 for sources following a subphotospheric energy spectrum with a mean energy of 100 GeV and a bolometric energy of 1052 erg. 

**Comments**
Could be interesting to discuss about how they perform the search.

**Comment by grburgess** [comment]
## The Non Relativistic Interiors of Ultra-Relativistic Explosions: Extension to the Blandford McKee Solutions

https://arxiv.org/abs/2011.05990

The hydrodynamics of an ultrarelativistic flow, enclosed by a strong shock wave, are described by the well known Blandford-McKee solutions in spherical geometry. These solutions, however, become inaccurate at a distance ∼R/2 behind the shock wave, where R is the shock radius, as the flow approaches Newtonian velocities. In this work we find a new self-similar solution which is an extension to the Blandford-McKee solutions, and which describes the interior part of the blast wave, where the flow reaches mildly relativistic to Newtonian velocities. We find that the velocity profile of the internal part of the flow does not depend on the value of the shock Lorentz factor, Γ, and is accurate from r=0 down to a distance of R/Γ2 behind the shock. Despite the fact that the shock wave is in causal contact with the entire flow behind it, a singular point appears in the equations. Nevertheless, the solution is not required to pass through the singular point: for ambient density that decreases slowly enough, ρ∝r−k with k<12(5−10‾‾‾√)≅0.92, a secondary shock wave forms with an inflow at the origin.

### comments
This is very neat

**Comment by grburgess** [comment]
## Space-based Measurements of Neutron Lifetime: Approaches to Resolving the Neutron Lifetime AnomalySpace-based Measurements of Neutron Lifetime: Approaches to Resolving the Neutron Lifetime Anomaly

https://arxiv.org/abs/2011.06095

Free neutrons have a measured lifetime of 880 s, but disagreement between existing laboratory measurements of ~10 s have persisted over many years. This uncertainty has implications for multiple physics disciplines, including standard-model particle physics and Big-Bang nucleosynthesis. Space-based neutron lifetime measurements have been shown to be feasible using existing data taken at Venus and the Moon, although the uncertainties for these measurements of tens of seconds prevent addressing the current lifetime discrepancy. We investigate the implementation of a dedicated space-based experiment that could provide a competitive and independent lifetime measurement. We considered a variety of scenarios, including measurements made from orbit about the Earth, Moon, and Venus, as well as on the surface of the Moon. For a standard-sized neutron detector, a measurement with three-second statistical precision can be obtained from Venus orbit in less than a day; a one-second statistical precision can be obtained from Venus orbit in less than a week. Similarly precise measurements in Earth orbit and on the lunar surface can be acquired in less than 40 days (three-second precision) and ~300 days (one-second precision). Systematic uncertainties that affect a space-based neutron lifetime measurement are investigated, and the feasibility of developing such an experiment is discussed.

### Comments

It is really hard to measure the free neutron lifetime. This is fun.

**Comment by grburgess** [comment]
# Notes from discussion

#### A backscattering dominated prompt emission model for the prompt phase of Gamma ray bursts

Bjorn: how do the photons escape from the back of the cork and still be seen by the observer?
Moritz: How is a cork different than normal drill out process?
Jochen: How is this relativistic before shock break out?

Shall we have a longer discussion?
___

#### 
Search for sub–TeV neutrino emission from transient sources with three years of IceCube data

Francesco: what in the world are they doing?

___

#### GW190521 may be an intermediate mass ratio inspiral

Bjorn: Why do they use so many live points and why Dynesty? 
Burgess: Can we trust the modality?
Jochen: perhaps not all the physics is involved?

___

Move the differential source count paper to next week.
