### ISSUE TITLE
Feb 8 Papers

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#11]
### A cautionary tale in fitting galaxy rotation curves with Bayesian techniques: does Newton's constant vary from galaxy to galaxy?

https://arxiv.org/abs/2101.11644

The application of Bayesian techniques to astronomical data is generally non-trivial because the fitting parameters can be strongly degenerated and the formal uncertainties are themselves uncertain. An example is provided by the contradictory claims over the presence or absence of a universal acceleration scale (g†) in galaxies based on Bayesian fits to rotation curves. To illustrate the situation, we present an analysis in which the Newtonian gravitational constant GN is allowed to vary from galaxy to galaxy when fitting rotation curves from the SPARC database, in analogy to g† in the recently debated Bayesian analyses. When imposing flat priors on GN, we obtain a wide distribution of GN which, taken at face value, would rule out GN as a universal constant with high statistical confidence. However, imposing an empirically motivated log-normal prior returns a virtually constant GN with no sacrifice in fit quality. This implies that the inference of a variable GN (or g†) is the result of the combined effect of parameter degeneracies and unavoidable uncertainties in the error model. When these effects are taken into account, the SPARC data are consistent with a constant GN (and constant g†).

#### Comments:

Discovery that priors matter.

**Comment by grburgess** [comment]
### Monte-Carlo Applications for Partially Polarised Inverse External-Compton Scattering (MAPPIES) -- I. Description of the code and First Results

https://arxiv.org/abs/2102.00037

The radiation mechanisms responsible for the multiwavelength emission from relativistic jet sources are poorly understood. The modelling of the spectral energy distributions (SEDs) and light curves alone is not adequate to distinguish between existing models. Polarisation in the X-ray and γ-ray regime of these sources may provide new and unique information about the jet physics and radiation mechanisms. Several upcoming projects will be able to deliver polarimetric measurements of the brightest X-ray sources, including active galactic nuclei (AGN) jets and γ-ray bursts (GRBs). This article describes the development of a new Monte-Carlo code -- MAPPIES (Monte-Carlo Applications for Partially Polarised Inverse External-Compton Scattering) -- for polarisation-dependent Compton scattering in relativistic jet sources. Generic results for Compton polarisation in the Thomson and Klein-Nishina regimes are presented.

**Comment by grburgess** [comment]
### A more probable explanation" is still impossible to explain GN-z11-flash: in response to Steinhardt et al. (arXiv:2101.12738)

https://arxiv.org/abs/2102.01239

In Jiang et al. (2020), we reported a possible bright flash (hereafter GN-z11-flash) from a galaxy GN-z11 at z ~ 11. Recently, Steinhardt et al. (2021; arXiv:2101.12738) found 27 images with transient signals in Keck MOSFIRE archival data and claimed that GN-z11-flash was more likely from a moving object in our Solar system. We show that the Steinhardt et al.'s definition of the chance probability and their methodology of finding GN-z11-flash-like transients are problematic in several aspects. In particular, none of their transients is analogous to GN-z11-flash, and none of them is positionally coincident with a known object in their imaging data. In Jiang et al., we performed a comprehensive analysis of the origin of GN-z11-flash and ruled out, to the best of our knowledge, the possibility of known **man**-made objects or moving objects in the Solar system, based on all available information and our current understanding of these objects. Steinhardt et al. did not use such information and did not analyse the GN-z11-flash event itself. The majority of their transients are apparently low-Earth orbit satellites or aircrafts. Therefore, their analysis can neither prove nor disprove our results. Finally, we present a method to estimate the chance probability of finding GN-z11-flash-like transients in archival data. Based on this method and the archival data used by Steinhardt et al., we obtain a loose upper limit of the probability that actually support the original results of Jiang et al. (2020).

Related:
https://arxiv.org/abs/2101.12738

**Comment by grburgess** [comment]
### Testing the Strong Equivalence Principle: Detection of the External Field Effect in Rotationally Supported Galaxies

https://arxiv.org/abs/2009.11525


The Strong Equivalence Principle (SEP) distinguishes General Relativity from other viable theories of gravity. The SEP demands that the internal dynamics of a self-gravitating system under free-fall in an external gravitational field should not depend on the external field strength. We test the SEP by investigating the external field effect (EFE) in Milgromian dynamics (MOND), proposed as an alternative to dark matter in interpreting galactic kinematics. We report a detection of this EFE using galaxies from the Spitzer Photometry and Accurate Rotation Curves (SPARC) sample together with estimates of the large-scale external gravitational field from an all-sky galaxy catalog. Our detection is threefold: (1) the EFE is individually detected at 8σ to 11σ in "golden" galaxies subjected to exceptionally strong external fields, while it is not detected in exceptionally isolated galaxies, (2) the EFE is statistically detected at more than 4σ from a blind test of 153 SPARC rotating galaxies, giving a mean value of the external field consistent with an independent estimate from the galaxies' environments, and (3) we detect a systematic downward trend in the weak gravity part of the radial acceleration relation at the right acceleration predicted by the EFE of the MOND modified gravity. Tidal effects from neighboring galaxies in the ΛCDM context are not strong enough to explain these phenomena. They are not predicted by existing ΛCDM models of galaxy formation and evolution, adding a new small-scale challenge to the ΛCDM paradigm. Our results point to a breakdown of the SEP, supporting modified gravity theories beyond General Relativity.

**Comment by cescalara** [comment]
### Neutrino signal dependence on gamma-ray burst emission mechanism

https://arxiv.org/abs/2102.02223

Long duration gamma-ray bursts (GRBs) are among the least understood astrophysical transients powering the high-energy universe. To date, various mechanisms have been proposed to explain the observed electromagnetic GRB emission. In this work, we show that, although different jet models may be equally successful in fitting the observed electromagnetic spectral energy distributions, the neutrino production strongly depends on the adopted emission and dissipation model. To this purpose, we compute the neutrino production for a benchmark high-luminosity GRB in the internal shock model, including a dissipative photosphere as well as three emission components, in the jet model invoking internal-collision-induced magnetic reconnection and turbulence (ICMART), in the case of a magnetic jet with gradual dissipation, and in a jet with dominant proton synchrotron radiation. We find that the expected neutrino fluence can vary up to 1-1.5 orders of magnitude in amplitude and peak at energies ranging from 104 to 108 GeV. For our benchmark input parameters, none of the explored GRB models is excluded by the targeted searches carried out by the IceCube and ANTARES Collaborations. However, our work highlights the potential of high-energy neutrinos of pinpointing the underlying GRB emission mechanism and the importance of relying on different jet models for unbiased stacking searches.

#### Comments:

Interested in what you guys think about all these different models. Also maybe related to last weeks multi-messenger seminar on GRB searches in Antares.

**Comment by cescalara** [comment]
### A marginally fast-cooling proton-synchrotron model for prompt GRBs

https://arxiv.org/abs/2102.02501

A small fraction of GRBs with available data down to soft X-rays (∼0.5 keV) have been shown to feature a spectral break in the low-energy part (∼1−10 keV) of their prompt emission spectrum. The overall spectral shape is consistent with optically thin synchrotron emission from a population of particles that have cooled on a timescale comparable to the dynamic time to energies that are still much higher than their rest mass energy (marginally fast cooling regime). We consider a hadronic scenario and investigate if the prompt emission of these GRBs can originate from relativistic protons that radiate synchrotron in the marginally fast cooling regime. Using semi-analytical methods, we derive the source parameters, such as magnetic field strength and proton luminosity, and calculate the high-energy neutrino emission expected in this scenario. We also investigate how the emission of secondary pairs produced by photopion interactions and γγ pair production affect the broadband photon spectrum. We support our findings with detailed numerical calculations. Strong modification of the photon spectrum below the break energy due to the synchrotron emission of secondary pairs is found, unless the bulk Lorentz factor is very large (Γ≳103). Moreover, this scenario predicts unreasonably high Poynting luminosities because of the strong magnetic fields (106−107 G) that are necessary for the incomplete proton cooling. Our results strongly disfavor marginally fast cooling protons as an explanation of the low-energy spectral break in the prompt GRB spectra.

**Comment by BjoernBiltzinger** [comment]
## Probing the physical properties of the intergalactic medium using gamma-ray bursts

https://arxiv.org/abs/2102.02530

We use Gamma-ray burst (GRB) spectra total continuum absorption to estimate the key intergalactic medium (IGM) properties of hydrogen column density ($\mathit{N}\textsc{hxigm}$), metallicity, temperature and ionisation parameter over a redshift range of 1.6≤z≤6.3, using photo-ionisation (PIE) and collisional ionisation equilibrium (CIE) models for the ionised plasma. We use more realistic host metallicity, dust corrected where available, in generating the host absorption model, assuming that the host intrinsic hydrogen column density is equal to the measured ionisation corrected intrinsic neutral column from UV spectra ($\textit{N}\textsc{h}\/\ \textsc{i,ic}$). We find that the IGM property results are similar, regardless of whether the model assumes all PIE or CIE. The $\mathit{N}\textsc{hxigm}$ scales as $(1 + z)^{1.0\/\ -\/\ 1.9}$, with equivalent hydrogen mean density at z=0 of n0=1.8+1.5−1.2×10−7 cm−3. The metallicity ranges from $\sim0.1Z\sun$ at z∼2 to $\sim0.001Z\sun$ at redshift z>4. The PIE model implies a less rapid decline in average metallicity with redshift compared to CIE. Under CIE, the temperature ranges between 5.0< log(T/K$)<\/\ 7.1$. For PIE the ionisation parameter ranges between 0.1< log(ξ)<2.9. Using our model, we conclude that the IGM contributes substantially to the total absorption seen in GRB spectra and that this contribution rises with redshift, explaining why the hydrogen column density inferred from X-rays is substantially in excess of the intrinsic host contribution measured in UV.
