### ISSUE TITLE
Mar 8 Papers

### ISSUE THREAD

**Issue by cescalara** [grburgess/awesome-reading-group#15]
### Prospects for kilonova signals in the gravitational-wave era

https://arxiv.org/abs/2103.00943

The binary neutron star merger gravitational-wave signal GW170817 was followed by three electromagnetic counter-parts, of which a kilonova arising from the radioactivity of freshly synthesized r-process elements in ejecta from the merger. Finding kilonovae after gravitational-wave triggers is crucial (i) to the search for further counterparts such as the afterglow, (ii) to probe the diversity of kilonovae and their dependence on the system's inclination angle (iii) to build a sample for multimessenger cosmology. During the third observing run of the gravitational-wave interferometer network, no kilonova counterpart was found. We aim to predict the expected population of detectable kilonova signals for the upcoming O4 and O5 observing runs of the LIGO-Virgo-Kagra instruments. Using a a simplified criterion for gravitational-wave detection and a simple GW170817-calibrated model for the kilonova peak magnitude, we determine the rate of kilonovae in reach of follow-up campaigns and their distributions in magnitude for various bands. We briefly consider the case of GW190425, the only confirmed binary neutron star merger since GW170817, and obtain constraints on its inclination angle from the non-detection of its kilonova, assuming the source was below the follow-up thresholds. We also show that non gravitational-wave-triggered kilonovae can be a numerous class of sources in the future surveys and briefly discuss associations with short bright gamma-ray bursts. We finally discuss the detection of the jetted outflow afterglow in addition to the kilonova, and confirm former conclusions on the rareness of such counterparts in future observations.

#### Comments:

More population/rate modelling stuff

**Comment by BjoernBiltzinger** [comment]
# EVIDENCE OF EXTENDED EMISSION IN GRB 181123B AND OTHER HIGH-REDSHIFT SHORT GRBS 

https://arxiv.org/abs/2103.02558


We study the high-energy properties of GRB 181123B, a short gamma-ray burst (sGRB) at redshift z ≈1.75. We show that, despite its nominal short duration with T90 < 2 s, this burst display evidence of a temporally extended emission (EE) at high energies and that the same trend is observed in the majority of sGRBs at z &1. We discuss the impact of instrumental selection effects on the GRB classification, stressing that the measured T90 is not an unambiguous indicator of the burst physical origin. By examining their environment (e.g. stellar mass, star formation, offset distribution), we find that these high-z sGRBs share many properties of long GRBs at a similar distance and are consistent with a short-lived progenitor system. If produced by compact binary mergers, these sGRBs with EE may herald a larger population of sGRBs in the early universe.
