### ISSUE TITLE
March 15 Paper

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#16]
### Predicting spectral parameters in the backscattering dominated model for the prompt phase of GRBs

https://arxiv.org/abs/2103.06201

We propose a model in which the photons generated through pair annihilation at the centre of a gamma ray burst (GRB) are backscattered through Compton scattering by an outflowing stellar cork. Using pair annihilation spectrum for seed photons, we show that the obtained spectra are capable of reproducing the low energy slopes in the observed prompt spectra of most GRBs. We predict that the low energy photon index ({\alpha}) ranges typically between 0.2 and -1.65 while the high energy slopes \beta are steeper. The Spectral peak energies ({\epsilon} peak ) cover a range from a few 10 x KeV to few MeV. Surveys have shown that the population of most bursts reside within these ranges. We further predict steep decay of photon flux at very low energies.

#### Comments:

Amazing.

**Comment by grburgess** [comment]
## The variable absorption in the X-ray spectrum of GRB 190114C

https://arxiv.org/abs/2103.05735

GRB 190114C was a bright burst that occurred in the local Universe (z=0.425). It was the first gamma-ray burst (GRB) ever detected at TeV energies, thanks to MAGIC. We characterize the ambient medium properties of the host galaxy through the study of the absorbing X-ray column density. Joining Swift, XMM-Newton, and NuSTAR observations, we find that the GRB X-ray spectrum is characterized by a high column density that is well in excess of the expected Milky Way value and decreases, by a factor of ~2, around ~105 s. Such a variability is not common in GRBs. The most straightforward interpretation of the variability in terms of photoionization of the ambient medium is not able to account for the decrease at such late times, when the source flux is less intense. Instead, we interpret the decrease as due to a clumped absorber, denser along the line of sight and surrounded by lower-density gas. After the detection at TeV energies of GRB 190114C, two other GRBs were promptly detected. They share a high value of the intrinsic column density and there are hints for a decrease of the column density, too. We speculate that a high local column density might be a common ingredient for TeV-detected GRBs.

### comments:


GRBs are magical and surrounded by fairy dust.

**Comment by cescalara** [comment]
### Radio Observations of an Ordinary Outflow from the Tidal Disruption Event AT2019dsg

https://arxiv.org/abs/2103.06299

We present detailed radio observations of the tidal disruption event (TDE) AT2019dsg, obtained with the Very Large Array (VLA) and the Atacama Large Millimeter/submillimeter Array (ALMA), and spanning 55−560 days post-disruption. We find that the peak brightness of the radio emission increases until ~200 days and subsequently begins to decrease steadily. Using the standard equipartition analysis, including the effects of synchrotron cooling as determined by the joint VLA-ALMA spectral energy distributions, we find that the outflow powering the radio emission is in roughly free expansion with a velocity of ≈0.07c, while its kinetic energy increases by a factor of about 5 from 55 to 200 days and plateaus at ≈5×1048 erg thereafter. The ambient density traced by the outflow declines as ≈R−1.6 on a scale of ≈(1−4)×1016 cm (≈6300−25000 Rs), followed by a steeper decline to ≈6×1016 cm (≈37500 Rs). Allowing for a collimated geometry, we find that to reach even mildly relativistic velocities (Γ=2) the outflow requires an opening angle of θj≈2∘, which is narrow even by the standards of GRB jets; a truly relativistic outflow requires an unphysically narrow jet. The outflow velocity and kinetic energy in AT2019dsg are typical of previous non-relativistic TDEs, and comparable to those from Type Ib/c supernovae, raising doubts about the claimed association with a high-energy neutrino event.

#### Comments:

Highlights the importance of bigger-picture info in the neutrino association analysis.

**Comment by cescalara** [comment]
## HAWC observations of the acceleration of very-high-1energy cosmic rays in the Cygnus Cocoon

https://arxiv.org/abs/2103.06820

Cosmic rays with energies up to a few PeV are known to be accelerated within the Milky Way. Traditionally, it has been presumed that supernova remnants were the main source of very-high-energy cosmic rays but theoretically it is difficult to get protons to PeV energies and observationally there simply is no evidence to support the remnants as sources of hadrons with energies above a few tens of TeV. One possible source of protons with those energies is the Galactic Center region. Here we report observations of 1-100 TeV gamma rays coming from the 'Cygnus Cocoon', which is a superbubble surrounding a region of OB2 massive star formation. These gamma rays are likely produced by 10-1000 TeV freshly accelerated CRs originating from the enclosed star forming region Cygnus OB2. Hitherto it was not known that such regions could accelerate particles to these energies. The measured flux is likely originated by hadronic interactions. The spectral shape and the emission profile of the Cocoon changes from GeV to TeV energies, which reveals the transport of cosmic particles and historical activity in the superbubble.

### Comments:

Maybe it is not so difficult to get such high energy CRs/nu nearby...
