### ISSUE TITLE
March 29 ground breaking research 

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#18]
### The Fermi GBM Gamma-Ray Burst Spectral Catalog: 10 Years of Data

https://arxiv.org/abs/2103.13528

We present the systematic spectral analyses of gamma-ray bursts (GRBs) detected by the Fermi Gamma-Ray Burst Monitor (GBM) during its first ten years of operation. This catalog contains two types of spectra; time-integrated spectral fits and spectral fits at the brightest time bin, from 2297 GRBs, resulting in a compendium of over 18000 spectra. The four different spectral models used for fitting the spectra were selected based on their empirical importance to the shape of many GRBs. We describe in detail our procedure and criteria for the analyses, and present the bulk results in the form of parameter distributions both in the observer frame and in the GRB rest frame. 941 GRBs from the first four years have been re-fitted using the same methodology as that of the 1356 GRBs in years five through ten. The data files containing the complete results are available from the High-Energy Astrophysics Science Archive Research Center (HEASARC).

#### Comments:

Lots of progress in the last 10 years. Histograms of parameters now include colour.

**Comment by BjoernBiltzinger** [comment]
# The morphology of the X-ray afterglows and of the jetted GeV emission in long GRBs

https://arxiv.org/abs/2103.09142

We recall evidence that long gamma-ray bursts (GRBs) have binary progenitors and give new examples. Binary-driven hypernovae (BdHNe) consist of a carbon-oxygen core (COcore) and a neutron star (NS) companion. For binary periods ∼5 min, the COcore collapse originates the subclass BdHN I characterized by: 1) an energetic supernova (the "SN-rise"); 2) a black hole (BH), born from the NS collapse by SN matter accretion, leading to a GeV emission with luminosity LGeV=AGeVt−αGeV, observed only in some cases; 3) a new NS (νNS), born from the SN, originating the X-ray afterglow with LX=AXt−αX, observed in all BdHN I. We record 378 sources and present for four prototypes GRBs 130427A, 160509A, 180720B and 190114C: 1) spectra, luminosities, SN-rise duration; 2) AX, αX=1.48±0.32, and 3) the νNS spin time-evolution. We infer a) AGeV, αGeV=1.19±0.04; b) the BdHN I morphology from time-resolved spectral analysis, three-dimensional simulations, and the GeV emission presence/absence in 54 sources within the Fermi-LAT boresight angle. For 25 sources, we give the integrated and time-varying GeV emission, 29 sources have no GeV emission detected and show X/gamma-ray flares previously inferred as observed along the binary plane. The 25/54 ratio implies the GeV radiation is emitted within a cone of half-opening angle ≈60∘ from the normal to the orbital plane. We deduce BH masses 2.3-8.9 M⊙ and spin 0.27-0.87 by explaining the GeV emission from the BH energy extraction, while their time evolution validates the BH mass-energy formula.

**Comment by cescalara** [comment]
## HAWC observations of the acceleration of very-high-1energy cosmic rays in the Cygnus Cocoon

https://arxiv.org/abs/2103.06820

Cosmic rays with energies up to a few PeV are known to be accelerated within the Milky Way. Traditionally, it has been presumed that supernova remnants were the main source of very-high-energy cosmic rays but theoretically it is difficult to get protons to PeV energies and observationally there simply is no evidence to support the remnants as sources of hadrons with energies above a few tens of TeV. One possible source of protons with those energies is the Galactic Center region. Here we report observations of 1-100 TeV gamma rays coming from the 'Cygnus Cocoon', which is a superbubble surrounding a region of OB2 massive star formation. These gamma rays are likely produced by 10-1000 TeV freshly accelerated CRs originating from the enclosed star forming region Cygnus OB2. Hitherto it was not known that such regions could accelerate particles to these energies. The measured flux is likely originated by hadronic interactions. The spectral shape and the emission profile of the Cocoon changes from GeV to TeV energies, which reveals the transport of cosmic particles and historical activity in the superbubble.

### Comments:

In case you didn't already talk about this from a couple weeks ago....

**Comment by cescalara** [comment]
## Search for High-Energy Neutrino Emission from Radio-Bright AGN

https://arxiv.org/abs/2103.12813

We investigate the possibility that radio-bright active galactic nuclei (AGN) are responsible for the TeV--PeV neutrinos detected by IceCube. We use an unbinned maximum-likelihood-ratio method, 10 years of IceCube muon-track data, and 3388 radio-bright AGN selected from the Radio Fundamental Catalog. None of the AGN in the catalog have a large global significance. The two most significant sources have global significance of ≃ 1.5σ and 0.8σ, though 4.1σ and 3.8σ local significance. Our stacking analyses show no significant correlation between the whole catalog and IceCube neutrinos. We infer from the null search that this catalog can account for at most 30\% (95\% CL) of the diffuse astrophysical neutrino flux measured by IceCube. Moreover, our results disagree with recent work that claimed a 4.1σ detection of neutrinos from the sources in this catalog, and we discuss the reasons of the difference.

### Comments

Kind of interesting that they end up with a non-significant result even using the same analysis methods.
