### ISSUE TITLE
Post Zombie Jesus Papers

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#19]
### A note on some discrepancies in convolution models in X-ray spectral analysis

https://arxiv.org/abs/2103.14937

Convolution models are a powerful tool in many fields of spectral and image analysis owing to their wide applicability, and X-ray astrophysical spectral analysis is no exception. We found that relativistically broadened Fe Kα line profiles obtained through many convolution models both within and without Xspec show deviations from the profiles produced by their non-convolution counterparts. These discrepancies depend on the energy grid considered and on the shape of both kernel and underlying spectrum, but can reach as high as 10% of the flux in certain energy bins. We believe this effect to be worrying, considering how often these models are used to study spectral features of lower relative intensity, and advise great discretion in using them.

#### Comments:

Hmm. Hmm.

**Comment by grburgess** [comment]
### Prevalence of Extra Power-Law Spectral Components in Short Gamma-Ray Bursts

https://arxiv.org/abs/2103.15355

Prompt extra power-law (PL) spectral component is discovered in some bright gamma-ray bursts (GRBs), which usually dominates the spectral energy distribution below tens of keV or above ∼10 MeV. However, its origin is still unclear. In this letter, we present a systematic analysis for 13 \textit{Fermi} short GRBs as of August 2020, with significant keV--MeV and GeV detections at the prompt emission phase. We find that the extra PL component is a ubiquitous spectral feature for short GRBs, showing up in all 13 analyzed GRBs. The PL indices are mostly harder than −2.0, which may be well reproduced by considering the electromagnetic cascade induced by ultra-relativistic protons or electrons accelerated in the prompt emission phase. The average flux of these extra PL components positively correlates with that of the main spectral components, which implies they may share the same physical origin.

#### Comments:

I am ashamed I ever worked on 3ML

**Comment by grburgess** [comment]
### Search for neutrinos from the tidal disruption events AT2019dsg and AT2019fdr with the ANTARES telescope

https://arxiv.org/abs/2103.15526

On October 1, 2019, the IceCube Collaboration detected a muon track neutrino with high probability of being of astrophysical origin, IC191001A. After a few hours, the tidal disruption event (TDE) AT2019dsg, observed by the Zwicky Transient Facility (ZTF), was indicated as the most likely counterpart of the IceCube track. More recently, the follow-up campaign of the IceCube alerts by ZTF suggested a second TDE, AT2019fdr, as a promising counterpart of another IceCube muon track candidate, IC200530A, detected on May 30, 2020. These are the second and third associations between astrophysical sources and high-energy neutrinos after the compelling identification of the blazar TXS 0506+056. Here, the search for ANTARES neutrinos from the directions of AT2019dsg and AT2019fdr using a time-integrated approach is presented. As no significant evidence for space clustering is found in the ANTARES data, upper limits on the one-flavour neutrino flux and fluence are set.

#### Comments: 

Because when you do BS one, why not do it again?

**Comment by grburgess** [comment]
### GRB160203A: an exploration of lumpy space

https://arxiv.org/abs/2103.15431


![iu](https://user-images.githubusercontent.com/6764007/112963660-e247e480-9147-11eb-8d5e-1a246807d120.png)

**Comment by grburgess** [comment]
### A novel approach to investigate chemical inhomogeneities in GRB host galaxies: The Zabs−Zemiss relation

https://arxiv.org/abs/2103.15269

Models of chemical enrichment and inhomogeneity in high-redshift galaxies are challenging to constrain observationally. In this work, we discuss a novel approach to probe chemical inhomogeneities within long Gamma-Ray Burst (GRB) host galaxies, by comparing the absorption metallicity, Z_abs, from the GRB afterglow (which probes the environment along the line of sight) with the emission-line metallicity, Z_emiss, measured via slit spectroscopy. Using the IllustrisTNG simulation, the theoretical relationship between these metallicity metrics is explored for a range of GRB formation models, varying the GRB progenitor metallicity threshold. For galaxies with fixed Z_emiss, the median value of Z_abs depends strongly on the GRB progenitor threshold metallicity, with Z_abs significantly lower than Z_emiss for high metallicity hosts. Conversely, at fixed Z_abs, the median value of Z_emiss depends primarily on the metallicity distribution of galaxies in IllustrisTNG and their chemical inhomogeneities, offering a GRB-model-independent way to constrain these processes observationally. Currently, only one host galaxy has data for both absorption and emission metallicities (GRB121014A). We re-analyse the emission spectrum and compare the inferred metallicity Z_emiss to a recent Bayesian determination of Z_abs, finding log(Zemiss/Z⊙)=log(Zabs/Z⊙)+0.35+0.14−0.25, within ~2 standard deviations of predictions from the IllustrisTNG simulation. Future observations with the James Webb Space Telescope will be able to measure Z_emiss for 4 other GRB hosts with known Z_abs values, using ~2 hour observations. While small, the sample will provide preliminary constraints on the Z_abs-Z_emiss relation to test chemical enrichment schemes in cosmological simulations.

**Comment by grburgess** [comment]
### Evidence for an intermediate-mass black hole from a gravitationally lensed gamma-ray burst

https://www.nature.com/articles/s41550-021-01307-1

If gamma-ray bursts are at cosmological distances, they must be gravitationally lensed occasionally1,2. The detection of lensed images with millisecond-to-second time delays provides evidence for intermediate-mass black holes, a population that has been difficult to observe. Several studies have searched for these delays in gamma-ray burst light curves, which would indicate an intervening gravitational lens3,4,5,6. Among the ~104 gamma-ray bursts observed, there have been a handful of claimed lensing detections7, but none have been statistically robust. Here we present a Bayesian analysis identifying gravitational lensing in the light curve of GRB 950830. The inferred lens mass Ml depends on the unknown lens redshift zl, and is given by (1+𝑧l)𝑀l=5.5+1.7−0.9×104𝑀⊙ (90% credibility), which we interpret as evidence for an intermediate-mass black hole. The most probable configuration, with a lens redshift zl ≈ 1 and a gamma-ray burst redshift zs ≈ 2, yields a present-day number density of about 2.3+4.9−1.6×103Mpc−3 (90% credibility) with a dimensionless energy density 𝛺IMBH≈4.6+9.8−3.3×10−4. The false alarm probability for this detection is ~0.6% with trial factors. While it is possible that GRB 950830 was lensed by a globular cluster, it is unlikely as we infer a cosmic density inconsistent with predictions for globular clusters ΩGC ≈ 8 × 10−6 at 99.8% credibility. If a significant intermediate-mass black hole population exists, it could provide the seeds for the growth of supermassive black holes in the early Universe.


#### Comments:

No.

**Comment by cescalara** [comment]
### Do LIGO/Virgo black hole mergers produce AGN flares? The case of GW190521 and prospects for reaching a confident association

https://arxiv.org/abs/2103.16069

The recent report of an association of the gravitational-wave (GW) binary black hole (BBH) merger GW190521 with a flare in the Active Galactic Nuclei (AGN) J124942.3+344929 has generated tremendous excitement. However, GW190521 has one of the largest localization volumes amongst all of the GW events detected so far. The 90\% localization volume likely contains 7,400 unobscured AGN brighter than g≤20.5 AB mag, and it results in a ≳70% probability of chance coincidence for an AGN flare consistent with the GW event. We present a Bayesian formalism to estimate the confidence of an AGN association by analyzing a population of BBH events with dedicated follow-up observations. Depending on the fraction of BBH arising from AGNs, counterpart searches of (1)−(100) GW events are needed to establish a confident association, and more than an order of magnitude more for searches without followup (i.e, using only the locations of AGNs and GW events). Follow-up campaigns of the top ∼5% (based on volume localization and binary mass) of BBH events with total rest frame mass ≥50 M⊙ are expected to establish a confident association during the next LIGO/Virgo/KAGRA observing run (O4), as long as the true value of the fraction of BBH giving rise to AGN flares is >0.1. Our formalism allows us to jointly infer cosmological parameters from a sample of BBH events that include chance coincidence flares. Until the confidence of AGN associations is established, the probability of chance coincidence must be taken into account to avoid biasing astrophysical and cosmological constraints.

**Comment by grburgess** [comment]
### Standard GRB Spectral Models "Misused"?

https://arxiv.org/abs/2103.11091

The standard model characterizing the GRB spectrum invokes a four-free-parameters empirical function, so-called the Band model. One alternative model named cutoff power-law (CPL) implements a power-law plus an exponential cutoff. These functions obtain almost equally good fits, and are adopted in nearly all the GRB literature. Here, we reanalyze the sample defined in Li. (39 bursts including 944 spectra). We classify the spectra by two methods: (1) checking their corner-corner plots of the posteriors to determine well-constrained β (Band-better) and un-constrained β (CPL-better) categories; and (2) defining four groups by the different of deviance information criterion (DIC). We found α=−0.64±0.28 and log10(Ep)=log10(191)±0.41 for the Band-better spectra and α=−0.96±0.33 and log10(Ep)=log10(249)±0.40 for the CPL-better spectra. With the "Correct" model (the "better" one between Band and CPL) and v.v. the "Misused" model defined, we find significant deviations in parameter distributions and parameter relations for the Band-"Correct" and CPL-"Misused" cases. This means if a spectrum is best-described as Band, applying CPL to derive the spectral parameters will prominently deviate from their intrinsic shape, therefore affecting the physical interpretation. Our analysis indicates that the "better" model should be duly examined during GRB spectral analysis. In addition, the β distribution exhibits a bimodal structure containing Band-better and CPL-better spectra respectively, inferring Band and CPL both have physical origins.

#### Comments:
four-free-parameters is a bad attempt at German?

**Comment by grburgess** [comment]
### Nucleosynthesis constraints through γ-ray line measurements from classical novae

https://arxiv.org/abs/2104.00363

Classical novae are among the most frequent transient events in the Milky Way, and key agents of ongoing nucleosynthesis. Despite their large numbers, they have never been observed in soft γ-ray emission. Measurements of their γ-ray signatures would provide both, insights on explosion mechanism as well as nucleosynthesis products. Our goal is to constrain the ejecta masses of 7Be and 22Na from classical novae through their γ-ray line emissions at 478 and 1275 keV. We extract posterior distributions on the line fluxes from archival data of the INTEGRAL/SPI spectrometer telescope. We then use a Bayesian hierarchical model to link individual objects and diffuse emission and infer ejecta masses from the whole population of classical novae in the Galaxy. Individual novae are too dim to be detectable in soft γ-rays, and the upper bounds on their flux and ejecta mass uncertainties cover several orders of magnitude. Within the framework of our hierarchical model, we can, nevertheless, infer tight upper bounds on the 22Na ejecta masses, given all uncertainties from individual objects as well as diffuse emission, of <2.0×10−7M⊙ (99.85th percentile). In the context of ONe nucleosynthesis, the 22Na bounds are consistent with theoretical expectations, and exclude that most ONe novae happen on white dwarfs with masses around 1.35M⊙. The upper bounds from 7Be are uninformative. From the combined ejecta mass estimate of 22Na and its β+-decay, we infer a positron production rate of <5.5×1042e+s−1, which would make at most 10% of the total annihilation rate in the Milky Way.

#### Comments:

Could be the worst paper ever?

**Comment by cescalara** [comment]
### Unified thermal model for photohadronic neutrino production in astrophysical sources

https://arxiv.org/abs/2103.16577

High-energy astrophysical neutrino fluxes are, for many applications, modeled as simple power laws as a function of energy. While this is reasonable in the case of neutrino production in hadronuclear pp sources, it typically does not capture the behavior in photohadronic pγ sources: in that case, the neutrino spectrum depends on the properties of the target photons the cosmic rays collide with and on possible magnetic-field effects on the secondary pions and muons. We show that the neutrino production from known photohadronic sources can be reproduced by a thermal (black-body) target-photon spectrum if one suitably adjusts the temperature, thanks to multi-pion production processes. This allows discussing neutrino production from most known pγ sources, such as gamma-ray bursts, active galactic nuclei and tidal disruption events, in terms of a few parameters. We apply this thermal model to study the sensitivity of different classes of neutrino telescopes to photohadronic sources: we classify the model parameter space according to which experiment is most suitable for detection of a specific source class and demonstrate that different experiment classes, such as dense arrays, conventional neutrino telescopes, or radio-detection experiments, cover different parts of the parameter space. Since the model can also reproduce the flavor and neutrino-antineutrino composition, we study the impact on the track-to-shower ratio and the Glashow resonance.

#### Comments:

Apparently a blackbody is all you need!

**Comment by cescalara** [comment]
### Evidence of TeV Halos Around Millisecond Pulsars

https://arxiv.org/abs/2104.00014

Using data from the HAWC gamma-ray Telescope, we have studied a sample of 37 millisecond pulsars (MSPs), selected for their spindown power and proximity. From among these MSP, we have identified four which favor the presence of very high-energy gamma-ray emission at a level of (2Δln)1/2≥2.5. Adopting a correlation between the spindown power and gamma-ray luminosity of each pulsar, we performed a stacked likelihood analysis of these 37 MSPs, finding that the data supports the conclusion that these sources emit very high-energy gamma-rays at a level of (2Δln)1/2=4.24. Among sets of randomly selected sky locations within HAWC's field-of-view, less than 1\% of such realizations yielded such high statistical significance. Our analysis suggests that MSPs produce very high-energy gamma-ray emission with a similar efficiency to that observed from the Geminga TeV-halo, ηMSP=(0.39−1.08)×ηGeminga. This conclusion poses a significant challenge for pulsar interpretations of the Galactic Center gamma-ray excess, as it suggests that any population of MSPs potentially capable of producing the GeV excess would also produce TeV-scale emission in excess of that observed by HESS from this region. Future observations by CTA will be able to substantially clarify this situation.

#### Comments:

It is dark matter
