### ISSUE TITLE
19th April Papers

### ISSUE THREAD

**Issue by cescalara** [grburgess/awesome-reading-group#20]
### Extragalactic magnetic field constraints from ultra-high-energy cosmic rays from local galaxies

https://arxiv.org/abs/2104.05732

We interpret the correlation between local \sbg positions and ultra-high-energy cosmic ray (UHECR) directions, recently reported by the Pierre Auger Observatory, in terms of physical parameters: the local density of sources and the magnetic fields governing the UHECR propagation. We include a Galactic magnetic field model on top of a random extragalactic magnetic field description to determine the level of UHECR deflections expected from an ensemble of source positions. Besides deflections in magnetic fields, we also take into account energy losses with background photon fields as well as spectrum and composition measurements by Auger. We find consistency between the Auger anisotropy measurement and the local \sbg density for large extragalactic magnetic field strengths with B>0.6 nG (for a coherence length of 1 Mpc) at the 5σ confidence level. Larger source densities lead to more isotropic background and consequently allow for weaker extragalactic magnetic fields. However, the acceleration of UHECR by such abundant sources is more challenging to motivate. Too large source densities and extragalactic magnetic field strengths, on the other hand, are also disfavored as that decreases the expected level of anisotropy. This leads to upper limits of B<24 nG and ρ0<9.0⋅10−2 Mpc−3 at the 90% confidence level.

#### Comments:

Could maybe be cool to use this kind of approach in a likelihood-free inference way

**Comment by tsiegert** [comment]
**Nucleosynthesis constraints through γ-ray line measurements from classical novae**

https://arxiv.org/abs/2104.00363

Classical novae are among the most frequent transient events in the Milky Way, and key agents of ongoing nucleosynthesis. Despite their large numbers, they have never been observed in soft γ-ray emission. Measurements of their γ-ray signatures would provide both, insights on explosion mechanism as well as nucleosynthesis products. Our goal is to constrain the ejecta masses of 7Be and 22Na from classical novae through their γ-ray line emissions at 478 and 1275 keV. We extract posterior distributions on the line fluxes from archival data of the INTEGRAL/SPI spectrometer telescope. We then use a Bayesian hierarchical model to link individual objects and diffuse emission and infer ejecta masses from the whole population of classical novae in the Galaxy. Individual novae are too dim to be detectable in soft γ-rays, and the upper bounds on their flux and ejecta mass uncertainties cover several orders of magnitude. Within the framework of our hierarchical model, we can, nevertheless, infer tight upper bounds on the 22Na ejecta masses, given all uncertainties from individual objects as well as diffuse emission, of <2.0×10−7M⊙ (99.85th percentile). In the context of ONe nucleosynthesis, the 22Na bounds are consistent with theoretical expectations, and exclude that most ONe novae happen on white dwarfs with masses around 1.35M⊙. The upper bounds from 7Be are uninformative. From the combined ejecta mass estimate of 22Na and its β+-decay, we infer a positron production rate of <5.5×1042e+s−1, which would make at most 10% of the total annihilation rate in the Milky Way.

**Comments:**

I do explain things and have stuff for GBM to do in it.

**Comment by grburgess** [comment]
### Standard GRB Spectral Models "Misused"?

https://arxiv.org/abs/2103.11091

The standard model characterizing the GRB spectrum invokes a four-free-parameters empirical function, so-called the Band model. One alternative model named cutoff power-law (CPL) implements a power-law plus an exponential cutoff. These functions obtain almost equally good fits, and are adopted in nearly all the GRB literature. Here, we reanalyze the sample defined in Li. (39 bursts including 944 spectra). We classify the spectra by two methods: (1) checking their corner-corner plots of the posteriors to determine well-constrained β (Band-better) and un-constrained β (CPL-better) categories; and (2) defining four groups by the different of deviance information criterion (DIC). We found α=−0.64±0.28 and log10(Ep)=log10(191)±0.41 for the Band-better spectra and α=−0.96±0.33 and log10(Ep)=log10(249)±0.40 for the CPL-better spectra. With the "Correct" model (the "better" one between Band and CPL) and v.v. the "Misused" model defined, we find significant deviations in parameter distributions and parameter relations for the Band-"Correct" and CPL-"Misused" cases. This means if a spectrum is best-described as Band, applying CPL to derive the spectral parameters will prominently deviate from their intrinsic shape, therefore affecting the physical interpretation. Our analysis indicates that the "better" model should be duly examined during GRB spectral analysis. In addition, the β distribution exhibits a bimodal structure containing Band-better and CPL-better spectra respectively, inferring Band and CPL both have physical origins.

#### Comments:
four-free-parameters is a bad attempt at German?
