### ISSUE TITLE
May 3

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#22]
### Identification of high-energy astrophysical point sources via hierarchical Bayesian nonparametric clustering

https://arxiv.org/abs/2104.11492

The light we receive from distant astrophysical objects carries information about their origins and the physical mechanisms that power them. The study of these signals, however, is complicated by the fact that observations are often a mixture of the light emitted by multiple localized sources situated in a spatially-varying background. A general algorithm to achieve robust and accurate source identification in this case remains an open question in astrophysics. 
This paper focuses on high-energy light (such as X-rays and gamma-rays), for which observatories can detect individual photons (quanta of light), measuring their incoming direction, arrival time, and energy. Our proposed Bayesian methodology uses both the spatial and energy information to identify point sources, that is, separate them from the spatially-varying background, to estimate their number, and to compute the posterior probabilities that each photon originated from each identified source. This is accomplished via a Dirichlet process mixture while the background is simultaneously reconstructed via a flexible Bayesian nonparametric model based on B-splines. Our proposed method is validated with a suite of simulation studies and illustrated with an application to a complex region of the sky observed by the \emph{Fermi} Gamma-ray Space Telescope.

**Comment by BjoernBiltzinger** [comment]
### The warm-hot circumgalactic medium around EAGLE-simulation galaxies and its detection prospects with X-ray and UV line absorption

https://arxiv.org/abs/2004.05171

We use the EAGLE (Evolution and Assembly of GaLaxies and their Environments) cosmological simulation to study the distribution of baryons, and far-ultraviolet (O VI), extreme-ultraviolet (Ne VIII) and X-ray (O VII, O VIII, Ne IX, and Fe XVII) line absorbers, around galaxies and haloes of mass M200c=1011-1014.5M⊙ at redshift 0.1. EAGLE predicts that the circumgalactic medium (CGM) contains more metals than the interstellar medium across halo masses. The ions we study here trace the warm-hot, volume-filling phase of the CGM, but are biased towards temperatures corresponding to the collisional ionization peak for each ion, and towards high metallicities. Gas well within the virial radius is mostly collisionally ionized, but around and beyond this radius, and for O VI, photoionization becomes significant. When presenting observables we work with column densities, but quantify their relation with equivalent widths by analysing virtual spectra. Virial-temperature collisional ionization equilibrium ion fractions are good predictors of column density trends with halo mass, but underestimate the diversity of ions in haloes. Halo gas dominates the highest column density absorption for X-ray lines, but lower density gas contributes to strong UV absorption lines from O VI and Ne VIII. Of the O VII (O VIII) absorbers detectable in an Athena X-IFU blind survey, we find that 41 (56) per cent arise from haloes with M200c=1012.0-1013.5M⊙. We predict that the X-IFU will detect O VII (O VIII) in 77 (46) per cent of the sightlines passing M⋆=1010.5-1011.0M⊙ galaxies within 100 pkpc (59 (82) per cent for M⋆>1011.0M⊙). Hence, the X-IFU will probe covering fractions comparable to those detected with the Cosmic Origins Spectrograph for O VI.
