### ISSUE TITLE
7th June papers

### ISSUE THREAD

**Issue by cescalara** [grburgess/awesome-reading-group#26]
### A test of the hadronic origin of γ-rays from blazars with up to month-later follow-up of IceCube Alerts with Imaging Air Cherenkov Telescopes

https://arxiv.org/abs/2105.14043

The sources of IceCube neutrinos are as yet unknown. The multi-messenger observation of their emission in γ-rays can be a guide to their identification, as exemplified by the case of TXS 0506+056. We suggest a new method of searching for γ-rays with Imaging Air Cherenkov Telescopes from sources in coincidence with possible astrophysical neutrinos. We propose that searches of γ-rays are extended, from the current practice of only a few days, to up to one month from a neutrino alert. We test this strategy on simulated sources modeled after the blazar \emph{TXS 0506+056-like}, emitting neutrinos and γ-rays via photohadronic interactions: the γ-rays are subsequently reprocessed in the VHE range. Using MAGIC as a benchmark example, we show that current Cherenkov Telescopes should be able to detectγ-ray counterparts to neutrino alerts with a rate of approximately one per year. It has been proposed that the high-energy diffuse neutrino flux can be explained by ∼ 5\% of all blazars flaring in neutrinos once every 10 years, with a neutrino luminosity similar to that of TXS 0506+056 during the 2014-2015 neutrino flare. The implementation of our strategy could lead, over a timescale of one or few years, either to the detection of this subclass of blazars contributing to the diffuse neutrino flux, or to a constraint on this model.

**Comment by grburgess** [comment]
### Does the Geminga $γ$-ray halo imply slow diffusion around pulsars?

http://arxiv.org/abs/2106.02275v1

The propagation of cosmic-ray electrons and positrons in the proximity of the
Geminga pulsar is examined considering the transition from the quasi-ballistic,
valid for the most recently injected particles, to the diffusive transport
regime. For typical interstellar values of the diffusion coefficient, the
quasi-ballistic regime dominates the lepton distribution up to distances of a
few tens of parsec from the pulsar for particle energies above $\sim 10$ TeV.
When such transition is taken into account, a good fit to the HAWC $\gamma-$ray
data around Geminga is obtained without the need to invoke a strong suppression
of the diffusion coefficient.

**Comment by grburgess** [comment]
Revealing x-ray and gamma ray temporal and spectral similarities in the GRB 190829A afterglow

http://arxiv.org/abs/2106.02510v1

Gamma-ray bursts (GRBs), which are bright flashes of gamma rays from
extragalactic sources followed by fading afterglow emission, are associated
with stellar core collapse events. We report the detection of very-high-energy
(VHE) gamma rays from the afterglow of GRB 190829A, between 4 and 56 hours
after the trigger, using the High Energy Stereoscopic System (H.E.S.S.). The
low luminosity and redshift of GRB 190829A reduce both internal and external
absorption, allowing determination of its intrinsic energy spectrum. Between
energies of 0.18 and 3.3 tera-electron volts, this spectrum is described by a
power law with photon index of 2.07 $\pm$ 0.09, similar to the x-ray spectrum.
The x-ray and VHE gamma-ray light curves also show similar decay profiles.
These similar characteristics in the x-ray and gamma-ray bands challenge GRB
afterglow emission scenarios.

**Comment by grburgess** [comment]
### Data tracking in research: aggregation and use or sale of usage data by academic publishers

https://www.dfg.de/download/pdf/foerderung/programme/lis/datentracking_papier_en.pdf

Basically, even if Prof Greiner is not on Facebook, journals are doing the same kind of tracking and selling of your data.
