### ISSUE TITLE
Dec 21 JC

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#7]
### Paper Tile

link

abstract

**Comment by BjoernBiltzinger** [comment]
### A first-principle simulation of blast wave emergence at the photosphere of a neutron star merger

https://arxiv.org/abs/2012.01798

We present the first ab initio simulation of a radiation-mediated shock emerging at the photosphere of a relativistic outflow. The simulation is performed using our code radshock that follows fluid dynamics coupled to time-dependent radiative transfer, calculated with the Monte-Carlo method. We use the code to examine the radiative blast wave emerging from neutron star merger GW170817. It was previously proposed that the merger ejected a dark, relativistically expanding, homologous envelope, and then an explosion inside the envelope produced the observed gamma-ray burst GRB170817A. Our simulation demonstrates how the shock wave generates radiation as it propagates through the envelope, approaches its photosphere, releases the radiation, and collapses, splitting into two collisionless shocks of a microscopic thickness. We find the light curve and the spectral evolution of the produced gamma-ray burst; both are similar to the observed GRB~170817A.

**Comment by grburgess** [comment]
### Multi-dimensional population modelling using frbpoppy: magnetars can produce the observed Fast Radio Burst sky

https://arxiv.org/abs/2012.06396

Fast Radio Bursts (FRBs) are energetic, short, bright transients that occur frequently over the entire radio sky. The observational challenges following from their fleeting, generally one-off nature have prevented identification of the underlying sources producing the bursts. As the population of detected FRBs grows, the observed distributions of brightness, pulse width and dispersion measure now begin to take shape. Meaningful direct interpretation of these distributions is, however, made impossible by the selection effects that telescope and search pipelines invariably imprint on each FRB survey. Here we show that multi-dimensional FRB population synthesis can find a single, self-consistent population of FRB sources that can reproduce the real-life results of the major ongoing FRB surveys. This means that individual observed distributions can now be combined to derive the properties of the intrinsic FRB source population. The characteristics of our best-fit model for one-off FRBs agree with a population of magnetars. We extrapolate this model and predict the number of FRBs future surveys will find. For surveys that have commenced, the method we present here can already determine the composition of the FRB source class, and potentially even its subpopulations.

#### Comments:

populations with 2DKS tests

**Comment by grburgess** [comment]
### A possible bright ultraviolet flash from a galaxy at redshift z ~ 11

https://arxiv.org/abs/2012.06937

In the optical sky, minutes-duration transients from cosmological distances are rare. Known objects that give rise to such transients include gamma-ray bursts (GRBs), the most luminous explosions in the universe that have been detected at redshift as high as z ~ 9.4. These high-redshift GRBs and their associated emission can be used to probe the star formation and reionization history in the era of cosmic dawn. Here we report a near-infrared transient with an observed duration shorter than 245 s coincident with the luminous star-forming galaxy GN-z11 at z ~ 11. The telluric absorption shown in the near-infrared spectrum indicates its origin from above the atmosphere. We can rule out the possibility of known man-made objects or moving objects in the Solar system based on the observational information and our current understanding of the properties of these objects. Since some long-duration GRBs are associated with a bright ultraviolet (UV) or optical flash, we investigate the possibility that the detected signal arose from a rest-frame UV flash associated with a long GRB from GN-z11. Despite the very low probability of being a GRB, we find that the spectrum, brightness, and duration of the transient are consistent with such an interpretation. Our result may suggest that long GRBs can be produced as early as 420 million years after the Big Bang.

#### Comments: 

well.

**Comment by grburgess** [comment]
### A Resource for Creating a Website to Promote Your Scientific Work

https://arxiv.org/abs/2012.08553

Creating a website to promote one's scientific work has become commonplace in many scientific disciplines. A plethora of options exist for framework to generate your website content, hosting it, and registering a domain name. The goal of this document is to provide early career scientists (1) an overview of the current options for creating a website to promote their professional persona, and (2) general advice concerning website written content and one's web presence. To get a sense of how other scientists created their websites, I created a survey asking colleagues about the services they used to create their websites and advice they have for someone creating a website. I received 54 responses from 53 astronomers and one computer scientist of which 23 were in an academic position beyond postdoc (faculty, scientist, etc.), 1 was an individual research fellow, 4 were in their third postdoc, 4 were in their second postdoc, 16 were in their first postdoc, and 6 were graduate students. I report the results of this survey here.
