### ISSUE TITLE
Jan. 25 Papers

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#9]
### The KM3NeT Open Science System

https://arxiv.org/abs/2101.06751

The KM3NeT neutrino detectors are currently under construction at two locations in the Mediterranean Sea, aiming to detect the Cherenkov light generated by high-energy relativistic charged particles in sea water. The KM3NeT collaboration will produce scientific data valuable both for the astrophysics and neutrino physics communities as well as for the Earth and Sea science community. An Open Science Portal and infrastructure are under development to provide public access to open KM3NeT data, software and services. In this contribution, the current architecture, interfaces and usage examples are presented.

#### Comments:

Open science. A novel idea.

**Comment by grburgess** [comment]
## Temporal Evolution of Prompt GRB Polarization

https://arxiv.org/abs/2101.06777

The dominant radiation mechanism that produces the prompt emission in gamma-ray bursts (GRBs) remains a major open question. Spectral information alone has proven insufficient in elucidating its nature. Time-resolved linear polarization has the potential to distinguish between popular emission mechanisms, e.g., synchrotron radiation from electrons with a power-law energy distribution or inverse Compton scattering of soft seed thermal photons, which can yield the typical GRB spectrum but produce different levels of polarization. Furthermore, it can be used to learn about the outflow's composition (i.e. whether it is kinetic-energy-dominated or Poynting-flux-dominated) and angular structure. For synchrotron emission it is a powerful probe of the magnetic field geometry. Here we consider synchrotron emission from a thin ultrarelativistic outflow, with bulk Lorentz factor Γ(R)=Γ0(R/R0)−m/2≫1, that radiates a Band-function spectrum in a single (multiple) pulse(s) over a range of radii, R0≤R≤R0+ΔR. Pulse profiles and polarization evolution at a given energy are presented for a coasting (m=0) and accelerating (m=−2/3) thin spherical shell and for an off-axis top-hat jet with sharp as well as smooth edges in emissivity. Four different magnetic field configurations are considered, such as a locally ordered field coherent over angular scales θB≳1/Γ, a tangled field (B⊥) in the plane transverse to the radial direction, an ordered field (B∥) aligned in the radial direction, and a globally ordered toroidal field (Btor). All field configurations produce distinct polarization evolution with single (for B⊥ and B∥) and double (for Btor) 90∘ changes in the polarization position angle.

###  Comments

polar-1

**Comment by grburgess** [comment]
### Fitting very flexible models: Linear regression with large numbers of parameters


https://arxiv.org/abs/2101.07256

There are many uses for linear fitting; the context here is interpolation and denoising of data, as when you have calibration data and you want to fit a smooth, flexible function to those data. Or you want to fit a flexible function to de-trend a time series or normalize a spectrum. In these contexts, investigators often choose a polynomial basis, or a Fourier basis, or wavelets, or something equally general. They also choose an order, or number of basis functions to fit, and (often) some kind of regularization. We discuss how this basis-function fitting is done, with ordinary least squares and extensions thereof. We emphasize that it is often valuable to choose far more parameters than data points, despite folk rules to the contrary: Suitably regularized models with enormous numbers of parameters generalize well and make good predictions for held-out data; over-fitting is not (mainly) a problem of having too many parameters. It is even possible to take the limit of infinite parameters, at which, if the basis and regularization are chosen correctly, the least-squares fit becomes the mean of a Gaussian process. We recommend cross-validation as a good empirical method for model selection (for example, setting the number of parameters and the form of the regularization), and jackknife resampling as a good empirical method for estimating the uncertainties of the predictions made by the model. We also give advice for building stable computational implementations.

**Comment by cescalara** [comment]
### High-Energy Neutrino Production in Clusters of Galaxies

https://arxiv.org/abs/2101.07702

Clusters of galaxies can potentially produce cosmic rays (CRs) up to very-high energies via large-scale shocks and turbulent acceleration. Due to their unique magnetic-field configuration, CRs with energy ≤1017 eV can be trapped within these structures over cosmological time scales, and generate secondary particles, including neutrinos and gamma rays, through interactions with the background gas and photons. In this work, we compute the contribution from clusters of galaxies to the diffuse neutrino background. We employ three-dimensional cosmological magnetohydrodynamical simulations of structure formation to model the turbulent intergalactic medium. We use the distribution of clusters within this cosmological volume to extract the properties of this population, including mass, magnetic field, temperature, and density. We propagate CRs into this environment using multi-dimensional Monte Carlo simulations across different redshifts (from z∼5 to z=0), considering all relevant photohadronic, photonuclear, and hadronuclear interaction processes. For CRs injected with a power-law energy spectrum ∝E−2, we find that clusters contribute to the diffuse flux observed by the IceCube Neutrino Observatory with up to ∼20%. On the other hand, for a CR spectrum ∝E−1.5, our results are compatible with the observed flux of IceCube, though most of the contribution comes from clusters with M≳1014M⊙ and redshift z≲0.3. These results suggest that clusters of galaxies can account for a sizeable fraction of the diffuse neutrino background.

**Comment by cescalara** [comment]
### Evidence that Ultra-High-Energy Gamma Rays are a Universal Feature Near Powerful Pulsars

https://arxiv.org/abs/2101.07895

The highest-energy known gamma-ray sources are all located within 0.5 degrees of extremely powerful pulsars. This raises the question of whether ultra-high-energy (UHE; > 56 TeV) gamma-ray emission is a universal feature expected near pulsars with a high spin-down power. Using four years of data from the High Altitude Water Cherenkov (HAWC) Gamma-Ray Observatory, we present a joint-likelihood analysis of ten extremely powerful pulsars to search for UHE gamma-ray emission correlated with these locations. We report a significant detection (> 3σ), indicating that UHE gamma-ray emission is a generic feature of powerful pulsars. We discuss the emission mechanisms of the gamma rays and the implications of this result. The individual environment that each pulsar is found in appears to play a role in the amount of emission.

**Comment by grburgess** [comment]
### A comprehensive view of blackbody components in the X-ray spectra of GRBs

https://arxiv.org/abs/2101.08296

A small fraction of gamma-ray bursts (GRBs) exhibit blackbody emission in the X-ray spectra, the origin of which is debated. In order to gain a more complete understanding of this phe- nomenon, we present a search for blackbody components in 116 GRBs with known redshifts observed by Swift XRT. A time-resolved spectral analysis is carried out and the significance of the blackbody is assessed with respect to an absorbed power-law model. We report nine new detections and confirm the previously reported blackbody in GRB 171205A. Together with our previous results, there are a total of 19 GRBs with significant blackbody emission in a sample of 199 GRBs observed by Swift over 13 years. The detections include one short GRB and two low-luminosity GRBs. We estimate fireball parameters from the blackbody components and note that the blackbody luminosity is correlated with the temperature and inferred Lorentz factor. There is a large spread in the properties of the blackbody components and the light curves, which points to different origins for the emission. In about a third of the GRBs, the blackbody is clearly associated with late prompt emission from the jet. The rest of the sample includes cases that are fully consistent with the expectations from a cocoon, as well cases that may be explained by high-latitude emission or more energetic cocoons. These results indicate that thermal emission is associated with all parts of the jet.

#### Comments:

```All spectra were grouped to a minimum of 20 counts per bin to enable the use of 𝜒2 statistics.```

![image](https://user-images.githubusercontent.com/6764007/105453607-b5c3a800-5c80-11eb-82f4-3e605050b140.png)

**Comment by grburgess** [comment]
### Practical Provenance in Astronomy

https://arxiv.org/abs/2101.08691

ecently the International Virtual Observatory Alliance (IVOA) released a standard to structure provenance metadata, and several implementations are in development in order to capture, store, access and visualize the provenance of astronomy data products. This BoF will be focused on practical needs for provenance in astronomy. A growing number of projects express the requirement to propose FAIR data (Findable, Accessible, Interoperable and Reusable) and thus manage provenance information to ensure the quality, reliability and trustworthiness of this data. The concepts are in place, but now, applied specifications and practical tools are needed to answer concrete use cases. During this session we discussed which strategies are considered by projects (observatories or data providers) to capture provenance in their context and how a end-user might query the provenance information to enhance her/his data selection and retrieval. The objective was to identify the development of tools and formats now needed to make provenance more practical needed to increase provenance take-up in the astronomical domain.

#### Comments:

good data practices
